//@ts-check
import Head from 'next/head'
import styles from "../../styles/Home.module.css"
import show from "../../styles/show.module.css"
import data from "../../database/data"
import mapSubject from "../../database/mapSubject"

export default function Subject(props) {
  const subject = mapSubject(props["data"]);//中身はdatabase/mapSubject.ts
  const syllabusUrl = "https://www.wsl.waseda.jp/syllabus/JAA104.php?pKey=" +subject["url_code"];

  return (
    <div className={styles.container}>
      <Head>
        <title>{subject["name"]}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={show['title-container']}>
          <h1>{subject["name"]}</h1>
          <h3>{subject["professor"]}</h3>
          <h3>{subject["semester"]}</h3>
          <h3>{subject["period"]}</h3>
        </div>
        <div className='analysis-container'>
          <div className='learning'></div>
        </div>
        <div className='analysis-container'>
          <div className='lecture'></div>
        </div>
        <div className='analysis-container'>
          <div className='syllabus'>
            <p>{subject["grade"]}</p>
            <a href={"https://www.wsl.waseda.jp/syllabus/JAA104.php?pKey=" +subject['url_code'] } target="_blank" >{"https://www.wsl.waseda.jp/syllabus/JAA104.php?pKey=" +subject['url_code'] }</a>
            <br/>
          </div>
        </div>
        <div className='other-classes'>
          <div className='other-class'></div>
          <div className='other-class'></div>
          <div className='other-class'></div>
        </div>
      </main>
    </div>
  )
}

export async function getStaticPaths() {
  return {
    paths: [
      {
        params: {
          url_code: "9S120300290120219S120300299S"
        },
      }
    ],
    fallback: false
  }
}

export async function getStaticProps({ params }) {
  const url_code = await params.url_code
  return {
    props: {
      data: data[url_code]
    }
  }
}