//@ts-check
import Head from 'next/head'
import styles from "../../styles/Home.module.css"

export default function Subject(props) {
  return (
    <div className={styles.container}>
      <Head>
        <title>{props["subject_name"]}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className='title-container'>
          <h1>{props["subject_name"]}</h1>
          <h3>{props["professor"]}</h3>
          <h3>{props["gakki"]}</h3>
          <h3>{props["koma"]}</h3>
        </div>
        <div className='analysis-container'>
          <div className='learning'></div>
        </div>
        <div className='analysis-container'>
          <div className='lecture'></div>
        </div>
        <div className='analysis-container'>
          <div className='syllabus'>
            <p>{props["grade"]}</p>
            <a href= "https://www.wsl.waseda.jp/syllabus/JAA104.php?pKey = {props['url_code']}" target="_blank" >https://www.wsl.waseda.jp/syllabus/JAA104.php?pKey = {props["url_code"]}</a>
          </div>
        </div>
        <div className='other-classes'>
          <div className='other-class'></div>
          <div className='other-class'></div>
          <div className='other-class'></div>
        </div>
      </main>
    </div>
  )
}

export async function getStaticPaths() {
  return {
    paths: [
      {
        params: {
          url_code: "9S120200190120219S120200199S"
        },
      }
    ],
    fallback: false
  }
}

export async function getStaticProps({ params }) {
  const url_code = await params.url_code
  const now = new Date()
  const date = `${now.getFullYear()}/${now.getMonth()+1}/${now.getDate()} ${now.getHours()}:${now.getMinutes()}:${now.getSeconds()}`
  
  return {
    props: {
      timestamp: date,
      url_code: "9S120200190120219S120200199S",
      year: "2021年度",
      graduate: "グローバルエデュケーションセンター",
      subject_name: "「たくましい知性を鍛える」演習　４",
      professor: "村田　信之",
      gakki: "冬クォーター",
      koma: "月２時限",
      subject_type: "人間的力量科目（リーダーシップ）",
      divided_year: "１年以上",
      units: 1,
      room: "７-３０３",
      campus: "早稲田",
      subject_key: "9S12020019",
      class_code: "1",
      language: "日本語",
      class_method: "対面",
      course_code: "GENX306S",
      large_field: "総合／学際",
      middle_field: "総合／学際",
      small_field: "総合／学際",
      level: "上級レベル",
      class_type: "演習／ゼミ",
      subtitle: "お互いのたくましい知性を鍛えあう",
      discription: "この演習は、「たくましい知性を鍛える1〜4」（金曜日5、6限）をすでに履修し終わった学生を対象としています。履修済みではない場合、「たくましい知性を鍛える1〜4」を同時に科目登録してください。＜この演習を表すキーワード＞学生がプレゼンする授業、後悔のない大学生活、アクティブラーニング、新しい発見、自己実現、情熱、熱狂、先輩とのつながりこの演習では、プレゼンテーション、ファシリテーション、マネジメント能力、リーダーシップを身につけます。具体的には、教室でそれらの基礎を学びながら、実際に自分でプロジェクトを動かしていき、その過程や運営方法などさまざまな情報をプレゼンテーションしてゼミ生で共有し、それに対してフィードバックすることによって、より深い知見を身につけていきます。ここでいうプロジェクトとは、「たくましい知性を鍛える」のプロジェクトでもいいし、学内外のプロジェクトでも、インターンやアルバイトやサークルでも、いわゆる「myプロジェクト」としてかまいません。また、ワークショップを実施することによってチームビルディングを行い、組織開発を視野に入れながら、ゼミ生相互のメンバーシップとモチベーションを高く保つようにする。そのため、ゲスト講師をお招きすることもあるし、自分たちで習得した知識や体験を共有するためのプレゼンテーションやディスカッションなども積極的に取り入れていきます。この演習では、自分のたくましい知性を鍛えながら、他者（ゼミ生、講義生）のたくましい知性も鍛え、お互いに人間的力量を育んでいきます。また、この演習では、田植えと稲刈りをします。田植え足袋をはいて田んぼに入り、みんなで並んで、いっせいに手で植えていきます。夏の終わりごろ、その弱々しかった苗がしっかりとした稲穂になり、これもカマを使って手で刈り取っていきます。日本という国の食料自給率は38%です。輸入に頼っていて、もし輸入先の国が売ってくれなくなったら、というシミュレーションは悲惨なものです。ところで、あなたの食料自給率は何%ですか？田植え稲刈りをすることによって、にぶってしまっている五感をシャープに取り戻し、食べ物を自分でつくる力をつけ、たくましい知性を鍛え、しなやかな感性を磨くために、合宿を行います（新コロナ感染拡大状況によります）。詳細は第1回目の演習時に説明します。",
      target: `この演習の到達目標は以下の３つです。
      (1)学生が自分たちで演習を作る
      (2)プレゼンテーション、ファシリテーション、マネジメント能力、リーダーシップを習得する
      (3)他者のたくましい知性を鍛える
      `,
      pp_learning: "事前・事後学習のためのサブゼミを設置することもあります。詳細は演習開講後に説明します。",
      plan: `この演習は、「たくましい知性を鍛える1〜4」（金曜日5、6限）をすでに履修し終わった学生を対象としています。
      履修済みではない場合、「たくましい知性を鍛える1〜4」を同時に科目登録してください。
      基本的に全回、講義、プレゼンテーション、ワークショップとディスカッションをし、必ずフィードバックの時間をとります。
      ＜参考：2020年度全日程＞
      【春クォーター】
      第1回：ゲスト講師：信岡良亮さん（さとのば大学）
      第2回：myプロジェクトプレゼンテーション
      第3回：ゲスト講師：さたけきみこさん（歌舞伎愛好家）
      第4回：myプロジェクトプレゼンテーション
      第5回：myプロジェクトプレゼンテーション
      第6回：myプロジェクトプレゼンテーション
      【夏クォーター】
      第1回：ゲスト講師：南祐貴さん（元博報堂、起業家）
      第2回：myプロジェクトプレゼンテーション
      第3回：ゲスト講師：梶川奈津子さん（リクルート　大隈塾OG）
      第4回：myプロジェクトプレゼンテーション
      第5回：ゲスト講師：工藤拓真さん（電通、クリエイティブブティック　大隈塾OB）
      第6回：myプロジェクトプレゼンテーション
      【秋クォーター】
      第1回：ゲスト講師：渋澤健さん（コモンズ投信株式会社会長）
      第2回：グループワーク「体験の言語化を体験する」
      第3回：myプロジェクトプレゼンテーション
      第4回：ゲスト講師：周涵さん（ニューラルポケット取締役COO）
      第5回：myプロジェクトプレゼンテーション
      第6回：myプロジェクトプレゼンテーション
      第7回：ゲスト講師：木村公洋さん（合同会社TEENAGE EMOTION代表、構成作家）
      第8回：myプロジェクトプレゼンテーション
      【冬クォーター】
      第1回：ゲスト講師：田村浩二さん（ミスターチーズケーキ）
      第2回：ゲスト講師：幡野広志さん（写真家）
      第3回：ゲスト講師：伊藤愛子さん（ニューハーフ、接客コンサルタント）
      第4回：myプロジェクトプレゼンテーション
      第5回：myプロジェクトプレゼンテーション
      第6回：ゲスト講師：小寺智子さん（株式会社講談社第一事業局　アーティスト企画部）
      第7回：卒業生プレゼンテーション
      第8回：卒業生プレゼンテーション`,
      textbook: "特になし。",
      references: "特になし。",
      grade: "全回出席と時間厳守であることを求めます。病気その他やむを得ない場合はその限りではありません。成績は出席、授業への貢献で総合的に判断します。",
      remarks: "この演習は春、夏、秋、冬クォーターを継続して履修することを前提としています。また、「たくましい知性を鍛える」1〜4で、プロジェクトにしっかりと関与し、継続的に運営に関わる学生を求めます。https://student.stonesoup.tokyo/instagramhttp://www.instagram.com/ookuma_jukutwitterhttps://mobile.twitter.com/ookuma_jukufacebookhttps://www.facebook.com/ookuma.school/",
      open: "TRUE",
    }
  }
}