import Head from 'next/head'
import styles from '../styles/Home.module.css'
type Props = { timestamp: string }


export default function SSG(props: Props) {
  return (
    <div className={styles.container}>
      <Head>
        <title>New Page!!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>new!SSGページ</h1>
        <p> time: {props.timestamp}</p>
      </main>
    </div>
  )
}
export const getStaticProps = async context => {
  const now = new Date()
  const date = `${now.getFullYear()}/${now.getMonth()+1}/${now.getDate()} ${now.getHours()}:${now.getMinutes()}:${now.getSeconds()}`
  
  return {
    props: {
      timestamp: date,
    }
  }
}